#!/usr/bin/env python3
# Edward Motion's
#
#   ██████╗ ██╗      █████╗  ██████╗██╗  ██╗██████╗  ██████╗ ██╗  ██╗
#   ██╔══██╗██║     ██╔══██╗██╔════╝██║ ██╔╝██╔══██╗██╔═══██╗╚██╗██╔╝
#   ██████╔╝██║     ███████║██║     █████╔╝ ██████╔╝██║   ██║ ╚███╔╝
#   ██╔══██╗██║     ██╔══██╗██║     ██╔═██╗ ██╔══██╗██║   ██║ ██╔██╗
#   ██████╔╝███████╗██║  ██║╚██████╗██║  ██╗██████╔╝╚██████╔╝██╔╝ ██╗
#   ╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝
#
# SIGNAL INTERCEPT


def decode_signal():
    signal = [0x41, 0x43, 0x43, 0x45, 0x53, 0x53]
    payload = "".join(chr(c) for c in signal)
    return payload


def main():
    pritn(f"\033[92m[✓] SIGNAL DECODED: {decode_signal()} GRANTED\033[0m")
    print("\033[92m[✓] FIREWALL BYPASSED\033[0m")
    print("\033[92m[✓] SUCCESS\033[0m")


if __name__ == "__main__":
    main()
